### ISSUE TITLE
Feedback from first course delivery of lesson 1

### ISSUE THREAD

**Issue by cc-a** [ImperialCollegeLondon/grad_school_software_engineering_course#10]
This feedback is based on delivery of lesson 1 of the course via the graduate school on 20th Feb. Most attendees knew Python and had been programming for >1 year. Most attendees were using their own laptops and had successfully completed the setup instructions.

# Instructor/helper feedback on session
* Back and forthing between tools content and other was time consuming
* Some people still struggled to have a working setup at the end partly due to technical problems below
* ~~People found editing settings json files confusing~~
* Timings for tools and exercises much too short
* Did not get to design patterns
* ~~Code formatting example uses Numpy but this has been removed from environment.yml~~
* ~~Code formatting example doesn't lint cleanly even with numpy installed "Module 'numpy.random' has no 'random' member" (something to do with `extension-pkg-whitelist`?). `random_sample` works instead.~~
* ~~Code formatting example doesn't actually run - which some users were doing to check validity ("TypeError: can't multiply sequence by non-int of type 'str'")~~
* ~~Need to advise people not to create folders with spaces in their names~~
* ~~Need to use settings UI rather editing JSON (searching for "format" and ticking two boxes is 10x faster)~~
* Interleaving tools and principles was slightly jarring, and ended up with people with broken VS Code setups getting further and further behind
* ~~Some of the example code isn't syntactically correct (e.g. "Modifying an input argument" section: missing ":" after ndarray)~~

# Technical problems encountered
* Python extension not activating in VS code
* ~~Filenames with spaces broke conda instructions~~
* ~~Non-obvious errors when user tried to work in `C:\` rather than `C:\users\username\`~~
* The "run code" button was not displayed for some people - even with Python extension loaded

# Positive attendee feedback
* Good amount of helpers
* Lots of help
* Good exercises
* Good assistance provided when needed
* Provides some nice resources which are useful for coding
* Great materials
* Nice website setup
* Liked the section on modularity
* Very useful to understand how to code under virtual environment
* Dough example is good
* Very much liked the conceptual stuff about coding (rather than the dict example)
* Enjoyed learning how to turn vs code into more of an IDE than just an editor with a terminal - will definitely save me lots of time
* Good overall explanation
* Explanation is clear
* General knowledge

# Negative attendee feedback
* Maybe better example for the level of abstraction
* Design better examples
* Would prefer complex type examples and when bad/good
* It could be a bit confusing difficult for non-python users to follow
* Online instructions not really clear for those who're not used to software engineering in VS
* Setup instructions
* Could provide resources for Ubuntu
* Bit fast
* Bit fast
* Perhaps do this on research computing rather than local system
* VS code seems to be a bit too moody

# Suggestions
* Consolidate tools sections and place all of the necessary configuration together.
* Further simplify examples (remove type hinting for example, several people were unsure what it was)
* Reduce complexity of exercises (particularly dict in datastructures exercise)
* ~~Make configuration instructions clearer and remove references to settings.json.~~
* ~~In Tools-I make launching Anaconda Prompt and python interpreter more prominent~~
* Implement workarounds for technical issues where possible.
* Have a cloud environment with a working setup available when people are having local setup issues.

Anything to add @mwoodbri @jcohen02?

**Comment by mwoodbri** [comment]
Comments incorporated above

**Comment by jcohen02** [comment]
I don't see an edit option for above post so I'm providing a few additional points here:

### Instructor/helper feedback on session

 - Further to the point about editing settings files, it seemed that finding the settings files caused some issues. As pointed out above, I agree that changes to settings should focus on using the settings pane within VS Code where you can search for the setting in question and change it via a textbox or checkbox depending on the setting type.

### Technical problems encountered

 - Slight differences in VS Code UI across different machines/platforms - some people didn't have the "Run" button (the play button) visible or in the same place as shown on the demo screen.
 - Contrary to the point above about code formatting not running, I didn't see this and saw that people had the example working. However, after telling you to select "black" as the code formatter it then tells you to (optionally) set the format on save option. Several people were not setting this option since it was shown as optional but of course when you then save the pasted text from the webpage, formatting doesn't happen. It should be shown as a required step to select the "format on save" option.
 - Re: Python extension not activating in VS Code: I saw one example of this where it appeared that VS Code may have updated itself and the installed extension was perhaps not compatible with the updated version - there was no error, it just kept failing to start the extension. Once the extension was uninstalled and then re-installed it worked fine.

### Suggestions

 - Perhaps start with the code examples (the data types material), when things went straight into the packaging material, I think that was perhaps a little too in depth for the initial material
 - Maybe also start with the Windows set up instructions for people on lab PCs before beginning the main material.
 -

**Comment by mwoodbri** [comment]
#12 at least partially address the points of detail in ~~strikethrough~~ above. Other feedback to be considered during or after next cohort:

- VS Code
  - Ask Software Hub guys to update versions of Code and Python extension?
  - Strongly suggest that people use the lab machines if still having issues with their own after 10 minutes?
- Context switching between tools content and other material
  - Do all the tools sections stuff up-front, resulting in a fully-functioning Code setup that can be used for remainder of lesson?
- Lack of time for exercises
  - Make at least some of the Design Patterns section "further reading"?
- Some of the content too complex for novices
  - Remove type hints at least?
